name: Maven Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Add permissions 
      run: chmod +x gradlew
    
    - name: Execute Gradle publish
      run: ./gradlew publish
